import {Request,Response} from 'express';
import mongoose from 'mongoose';
import {ok} from '../utils/api.js';
import {AppError} from '../utils/errors.js';
import {Banner} from '../models/Banner.js';
import {Notification,NotificationRead} from '../models/Notification.js';
import {AdminSettings} from '../models/AdminSettings.js';
import {audit} from '../services/audit.service.js';
import {bannerCreateSchema,bannerUpdateSchema} from '../../../shared/schemas/content.js';

function activeWindowQuery(now=new Date()){return {$and:[{$or:[{startAt:null},{startAt:{$lte:now}}]},{$or:[{endAt:null},{endAt:{$gte:now}}]}]};}
function bannerPayload(req:Request){return {...req.body,active:req.body.active===undefined?undefined:req.body.active===true||req.body.active==='true',order:req.body.order===undefined?0:Number(req.body.order),...(req.file?{imageUrl:`/media/${req.file.filename}`}:(req.body.imageUrl!==undefined?{imageUrl:req.body.imageUrl}:{}))};}
function notificationStatus(n:any,now=new Date()){if(!n.active)return 'Inactive';if(n.startAt&&now<n.startAt)return 'Scheduled';if(n.endAt&&now>n.endAt)return 'Expired';return 'Active';}
export async function activeBanners(_req:Request,res:Response){const now=new Date();return ok(res,await Banner.find({active:true,...activeWindowQuery(now)}).sort({order:1,createdAt:-1}).lean());}
export async function activeNotifications(req:Request,res:Response){const now=new Date();const ns=await Notification.find({active:true,...activeWindowQuery(now)}).sort({createdAt:-1}).lean();const reads=await NotificationRead.find({userId:req.auth!.userId,notificationId:{$in:ns.map(n=>String(n._id))}}).lean();const by=new Map(reads.map(x=>[x.notificationId.toString(),x]));const visible=ns.filter(n=>{const r=by.get(String(n._id));if(!r)return true;if(r.dismissedAt&&n.frequency==='once')return false;if(n.frequency==='always')return !r.dismissedAt;if(n.frequency==='once')return false;const basis=(r.readAt??r.dismissedAt)?.getTime()??0;return Date.now()-basis>=n.repeatIntervalHours*3600000;});return ok(res,visible.map(n=>({...n,status:notificationStatus(n,now)})));}
export async function notificationHistory(req:Request,res:Response){const reads=await NotificationRead.find({userId:req.auth!.userId}).sort({updatedAt:-1}).limit(100).populate('notificationId').lean();return ok(res,reads.map((r:any)=>({...r.notificationId,readAt:r.readAt,dismissedAt:r.dismissedAt,status:'History'})));}
export async function readNotification(req:Request,res:Response){if(!mongoose.isValidObjectId(String(req.params.id)))throw new AppError(400,'Invalid notification identifier');const n=await Notification.findById(String(req.params.id)).lean();if(!n)throw new AppError(404,'Notification not found');const r=await NotificationRead.findOneAndUpdate({notificationId:String(req.params.id),userId:req.auth!.userId},{$set:{readAt:new Date()}},{upsert:true,new:true,setDefaultsOnInsert:true});return ok(res,r,'Notification marked as read');}
export async function dismissNotification(req:Request,res:Response){if(!mongoose.isValidObjectId(String(req.params.id)))throw new AppError(400,'Invalid notification identifier');const n=await Notification.findById(String(req.params.id)).lean();if(!n)throw new AppError(404,'Notification not found');const r=await NotificationRead.findOneAndUpdate({notificationId:String(req.params.id),userId:req.auth!.userId},{$set:{dismissedAt:new Date(),readAt:new Date()}},{upsert:true,new:true,setDefaultsOnInsert:true});return ok(res,r,'Notification dismissed');}
export async function createBanner(req:Request,res:Response){const parsed=bannerCreateSchema.safeParse(bannerPayload(req));if(!parsed.success)throw new AppError(422,'Validation failed',parsed.error.issues);if(!parsed.data.imageUrl)throw new AppError(422,'Banner image is required');const b=await Banner.create(parsed.data);await audit({actorId:req.auth!.userId,action:'banner.create',targetType:'Banner',targetId:b._id.toString(),after:b.toObject(),ip:req.ip,userAgent:req.get('user-agent')??undefined});return ok(res,b,'Banner created',201);}
export async function updateBanner(req:Request,res:Response){if(!mongoose.isValidObjectId(String(req.params.id)))throw new AppError(400,'Invalid banner identifier');const parsed=bannerUpdateSchema.safeParse(bannerPayload(req));if(!parsed.success)throw new AppError(422,'Validation failed',parsed.error.issues);const before=await Banner.findById(String(req.params.id)).lean();if(!before)throw new AppError(404,'Banner not found');const b=await Banner.findByIdAndUpdate(String(req.params.id),{$set:parsed.data},{new:true,runValidators:true});if(!b)throw new AppError(404,'Banner not found');await audit({actorId:req.auth!.userId,action:'banner.update',targetType:'Banner',targetId:b._id.toString(),before,after:b.toObject(),ip:req.ip,userAgent:req.get('user-agent')??undefined});return ok(res,b,'Banner updated');}
export async function setBannerStatus(req:Request,res:Response){if(!mongoose.isValidObjectId(String(req.params.id)))throw new AppError(400,'Invalid banner identifier');if(typeof req.body.active!=='boolean')throw new AppError(422,'active must be boolean');const before=await Banner.findById(String(req.params.id)).lean();if(!before)throw new AppError(404,'Banner not found');const b=await Banner.findByIdAndUpdate(String(req.params.id),{$set:{active:req.body.active}},{new:true});await audit({actorId:req.auth!.userId,action:'banner.status',targetType:'Banner',targetId:String(req.params.id),before,after:b!.toObject(),ip:req.ip,userAgent:req.get('user-agent')??undefined});return ok(res,b,'Banner status updated');}
export async function deleteBanner(req:Request,res:Response){if(!mongoose.isValidObjectId(String(req.params.id)))throw new AppError(400,'Invalid banner identifier');const b=await Banner.findByIdAndDelete(String(req.params.id));if(!b)throw new AppError(404,'Banner not found');await audit({actorId:req.auth!.userId,action:'banner.delete',targetType:'Banner',targetId:String(req.params.id),before:b.toObject(),ip:req.ip,userAgent:req.get('user-agent')??undefined});return ok(res,null,'Banner deleted');}
export async function publicSettings(_req:Request,res:Response){const s=await AdminSettings.findOne({key:'global'}).lean();return ok(res,{platformName:s?.platformName??'Nexus Member',paymentDetails:{jazzCashNumber:s?.paymentDetails?.jazzCashActive===false?'':s?.paymentDetails?.jazzCashNumber??'',jazzCashTitle:s?.paymentDetails?.jazzCashTitle??'',jazzCashActive:s?.paymentDetails?.jazzCashActive!==false,easypaisaNumber:s?.paymentDetails?.easypaisaActive===false?'':s?.paymentDetails?.easypaisaNumber??'',easypaisaTitle:s?.paymentDetails?.easypaisaTitle??'',easypaisaActive:s?.paymentDetails?.easypaisaActive!==false,instructions:s?.paymentDetails?.instructions??''},withdrawalsEnabled:s?.withdrawalsEnabled??true,withdrawalDisabledMessage:s?.withdrawalDisabledMessage??'',withdrawalFeePercent:s?.withdrawalFeePercent??10,minimumWithdrawal:s?.minimumWithdrawal??0,maximumWithdrawal:s?.maximumWithdrawal??100000000,withdrawalCooldownHours:s?.withdrawalCooldownHours??24,capitalLockDays:s?.capitalLockDays??30,whatsapp:s?.whatsapp??{enabled:false,url:''},telegram:s?.telegram??{enabled:false,url:''}});}



