import {Request,Response} from 'express'; import mongoose from 'mongoose';
import {env} from '../config/env.js'; import {ok} from '../utils/api.js'; import {AppError} from '../utils/errors.js';
import {Deposit} from '../models/Deposit.js'; import {Withdrawal} from '../models/Withdrawal.js'; import {Transaction} from '../models/Transaction.js'; import {AuditLog} from '../models/AuditLog.js';
import {Notification} from '../models/Notification.js'; import {Banner} from '../models/Banner.js'; import {User} from '../models/User.js'; import {audit} from '../services/audit.service.js'; import {withTransaction} from '../services/ledger.service.js';
import {notificationCreateSchema,notificationUpdateSchema} from '../../../shared/schemas/content.js';
function paging(req:Request){const rawPage=Number(req.query.page??1),rawLimit=Number(req.query.limit??25);const page=Number.isFinite(rawPage)&&rawPage>=1?Math.floor(rawPage):1;const limit=Number.isFinite(rawLimit)&&rawLimit>=1?Math.min(100,Math.floor(rawLimit)):25;return {page,limit,skip:(page-1)*limit};}
function dateRange(req:Request){const from=typeof req.query.from==='string'?new Date(req.query.from):null;const to=typeof req.query.to==='string'?new Date(req.query.to):null;if(from&&!isNaN(from.getTime()))from.setHours(0,0,0,0);if(to&&!isNaN(to.getTime()))to.setHours(23,59,59,999);return ((from&&!isNaN(from.getTime()))||(to&&!isNaN(to.getTime())))?{createdAt:{...(from&&!isNaN(from.getTime())?{$gte:from}:{}),...(to&&!isNaN(to.getTime())?{$lte:to}:{})}}:{};}
function escapedQuery(value:string){return value?new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i'):null;}
export async function adminDeposits(req:Request,res:Response){const {page,limit,skip}=paging(req);const status=typeof req.query.status==='string'&&['pending','approved','rejected'].includes(req.query.status)?req.query.status:undefined;const q=typeof req.query.q==='string'?req.query.q.trim().slice(0,100):'';const rx=escapedQuery(q);const memberIds=rx?await User.find({role:'member',$or:[{username:rx},{memberId:rx},{mobile:rx},{fullName:rx}]}).distinct('_id'):[];const query:any={...(status?{status}:{}),...(rx?{$or:[{reference:rx},{userId:{$in:memberIds}}]}:{}),...dateRange(req)};const [rawItems,total]=await Promise.all([Deposit.find(query).sort({createdAt:-1}).skip(skip).limit(limit).populate('userId','username memberId mobile fullName email address').lean(),Deposit.countDocuments(query)]);const items=rawItems.map(({receiptPath,...row})=>({...row,hasReceipt:Boolean(receiptPath)}));return ok(res,{items,total,page,limit,pages:Math.ceil(total/limit)});}
export async function adminWithdrawals(req:Request,res:Response){const {page,limit,skip}=paging(req);const status=typeof req.query.status==='string'&&['pending','approved','rejected','paid'].includes(req.query.status)?req.query.status:undefined;const q=typeof req.query.q==='string'?req.query.q.trim().slice(0,100):'';const rx=escapedQuery(q);const memberIds=rx?await User.find({role:'member',$or:[{username:rx},{memberId:rx},{mobile:rx},{fullName:rx}]}).distinct('_id'):[];const query:any={...(status?{status}:{}),...(rx?{$or:[{reference:rx},{userId:{$in:memberIds}}]}:{}),...dateRange(req)};const [items,total]=await Promise.all([Withdrawal.find(query).sort({createdAt:-1}).skip(skip).limit(limit).populate('userId','username memberId mobile fullName').lean(),Withdrawal.countDocuments(query)]);return ok(res,{items,total,page,limit,pages:Math.ceil(total/limit)});}
export async function adminTransactions(req:Request,res:Response){const {page,limit,skip}=paging(req);const type=typeof req.query.type==='string'?req.query.type:undefined;const status=typeof req.query.status==='string'&&['pending','approved','rejected','paid'].includes(req.query.status)?req.query.status:undefined;const query={...(type?{type}:{}),...(status?{status}: {})};const [items,total]=await Promise.all([Transaction.find(query).sort({createdAt:-1}).skip(skip).limit(limit).lean(),Transaction.countDocuments(query)]);return ok(res,{items,total,page,limit,pages:Math.ceil(total/limit)});}
export async function auditLogs(req:Request,res:Response){const {page,limit,skip}=paging(req);const [items,total]=await Promise.all([AuditLog.find().sort({createdAt:-1}).skip(skip).limit(limit).populate('actorId','username memberId').lean(),AuditLog.countDocuments()]);return ok(res,{items,total,page,limit,pages:Math.ceil(total/limit)});}
function statusFor(item:any){const now=new Date();if(!item.active)return 'Inactive';if(item.startAt&&now<new Date(item.startAt))return 'Scheduled';if(item.endAt&&now>new Date(item.endAt))return 'Expired';return 'Active';}
export async function createNotification(req:Request,res:Response){const parsed=notificationCreateSchema.safeParse(req.body);if(!parsed.success)throw new AppError(422,'Validation failed',parsed.error.issues);const n=await withTransaction(async session=>{const created=(await Notification.create([parsed.data],{session}))[0];await audit({actorId:req.auth!.userId,action:'notification.create',targetType:'Notification',targetId:created._id.toString(),after:created.toObject(),ip:req.ip,userAgent:req.get('user-agent')??undefined},{session});return created;});return ok(res,n,'Notification created',201);}
export async function updateNotification(req:Request,res:Response){if(!mongoose.isValidObjectId(String(req.params.id)))throw new AppError(400,'Invalid notification identifier');const parsed=notificationUpdateSchema.safeParse(req.body);if(!parsed.success)throw new AppError(422,'Validation failed',parsed.error.issues);const n=await withTransaction(async session=>{const before=await Notification.findById(String(req.params.id)).session(session).lean();if(!before)throw new AppError(404,'Notification not found');const updated=await Notification.findByIdAndUpdate(String(req.params.id),{$set:parsed.data},{new:true,runValidators:true,session});await audit({actorId:req.auth!.userId,action:'notification.update',targetType:'Notification',targetId:String(req.params.id),before,after:updated!.toObject(),ip:req.ip,userAgent:req.get('user-agent')??undefined},{session});return updated;});return ok(res,n,'Notification updated');}
export async function setNotificationStatus(req:Request,res:Response){if(!mongoose.isValidObjectId(String(req.params.id)))throw new AppError(400,'Invalid notification identifier');if(typeof req.body.active!=='boolean')throw new AppError(422,'active must be boolean');const n=await withTransaction(async session=>{const before=await Notification.findById(String(req.params.id)).session(session).lean();if(!before)throw new AppError(404,'Notification not found');const updated=await Notification.findByIdAndUpdate(String(req.params.id),{$set:{active:req.body.active}},{new:true,session});await audit({actorId:req.auth!.userId,action:'notification.status',targetType:'Notification',targetId:String(req.params.id),before,after:updated!.toObject(),ip:req.ip,userAgent:req.get('user-agent')??undefined},{session});return updated;});return ok(res,n,'Notification status updated');}
export async function deleteNotification(req:Request,res:Response){if(!mongoose.isValidObjectId(String(req.params.id)))throw new AppError(400,'Invalid notification identifier');await withTransaction(async session=>{const n=await Notification.findByIdAndDelete(String(req.params.id),{session});if(!n)throw new AppError(404,'Notification not found');await audit({actorId:req.auth!.userId,action:'notification.delete',targetType:'Notification',targetId:String(req.params.id),before:n.toObject(),ip:req.ip,userAgent:req.get('user-agent')??undefined},{session});});return ok(res,null,'Notification deleted');}
export async function listNotifications(_req:Request,res:Response){const rows=await Notification.find().sort({createdAt:-1}).limit(100).lean();return ok(res,rows.map(n=>({...n,status:statusFor(n)})));}
export async function listBanners(_req:Request,res:Response){const rows=await Banner.find().sort({order:1,createdAt:-1}).limit(200).lean();return ok(res,rows.map((b:any)=>({...b,status:statusFor(b)})));}
export async function depositReceipt(req:Request,res:Response){if(!mongoose.isValidObjectId(String(req.params.id)))return res.status(400).json({success:false,message:'Invalid deposit identifier'});const d=await Deposit.findById(String(req.params.id)).select('receiptPath');if(!d?.receiptPath)return res.status(404).json({success:false,message:'Receipt not found'});const safe=String(d.receiptPath);if(safe!==requireBasename(safe))return res.status(400).json({success:false,message:'Invalid receipt path'});return res.sendFile(safe,{root:env.UPLOAD_DIR});}
export async function memberDepositReceipt(req:Request,res:Response){if(!mongoose.isValidObjectId(String(req.params.id)))return res.status(400).json({success:false,message:'Invalid deposit identifier'});const d=await Deposit.findOne({_id:String(req.params.id),userId:req.auth!.userId}).select('receiptPath');if(!d?.receiptPath)return res.status(404).json({success:false,message:'Receipt not found'});const safe=String(d.receiptPath);if(safe!==requireBasename(safe))return res.status(400).json({success:false,message:'Invalid receipt path'});return res.sendFile(safe,{root:env.UPLOAD_DIR});}
function requireBasename(value:string){return value.split(/[\\/]/).pop()??'';}



