import {Request,Response} from 'express'; import mongoose from 'mongoose'; import {ok} from '../utils/api.js'; import {approveDeposit,rejectDeposit} from '../services/deposit.service.js'; import {processWithdrawal} from '../services/withdrawal.service.js'; import {dashboardStats,searchMembers,memberDetail} from '../services/admin.service.js'; import {getSettings,updateSettings} from '../services/settings.service.js'; import {AdminSettings} from '../models/AdminSettings.js';
export async function stats(_req:Request,res:Response){return ok(res,await dashboardStats());}
export async function members(req:Request,res:Response){const q=String(req.query.q??'').trim().slice(0,100);const rawPage=Number(req.query.page??1),rawLimit=Number(req.query.limit??20);const page=Number.isFinite(rawPage)&&rawPage>=1?Math.floor(rawPage):1;const limit=Number.isFinite(rawLimit)&&rawLimit>=1?Math.min(100,Math.floor(rawLimit)):20;return ok(res,await searchMembers(q,page,limit));}
export async function member(req:Request,res:Response){if(!mongoose.isValidObjectId(String(req.params.id)))return res.status(400).json({success:false,message:'Invalid member identifier'});const data=await memberDetail(String(req.params.id));return data?ok(res,data):res.status(404).json({success:false,message:'Member not found'});}
export async function approveDep(req:Request,res:Response){return ok(res,await approveDeposit(String(req.params.id),req.auth!.userId,req.body.note,{ip:req.ip,userAgent:req.get('user-agent')??undefined}));}
export async function rejectDep(req:Request,res:Response){return ok(res,await rejectDeposit(String(req.params.id),req.auth!.userId,req.body.note,{ip:req.ip,userAgent:req.get('user-agent')??undefined}));}
export async function approveWd(req:Request,res:Response){return ok(res,await processWithdrawal(String(req.params.id),req.auth!.userId,true,req.body.note,{ip:req.ip,userAgent:req.get('user-agent')??undefined}));}
export async function rejectWd(req:Request,res:Response){return ok(res,await processWithdrawal(String(req.params.id),req.auth!.userId,false,req.body.note,{ip:req.ip,userAgent:req.get('user-agent')??undefined}));}
export async function settings(_req:Request,res:Response){return ok(res,await getSettings());}
export async function updateSettingsController(req:Request,res:Response){const result=await updateSettings(req.body,req.auth!.userId,{ip:req.ip,userAgent:req.get('user-agent')??undefined});return ok(res,result.settings,'Settings updated');}
export async function withdrawalStatus(_req:Request,res:Response){return ok(res,await AdminSettings.findOne({key:'global'}).select('withdrawalsEnabled withdrawalDisabledMessage withdrawalFeePercent minimumWithdrawal maximumWithdrawal withdrawalCooldownHours capitalLockDays').lean());}

