import crypto from 'node:crypto'; import mongoose,{ClientSession} from 'mongoose'; import {Wallet} from '../models/Wallet.js'; import {Transaction} from '../models/Transaction.js'; import {AppError} from '../utils/errors.js'; import {money as preciseMoney} from '../utils/financial-rules.js';
export function money(n:number){return preciseMoney(n);}
export async function ensureWallet(userId:unknown,session?:ClientSession){let q=Wallet.findOne({userId});if(session)q=q.session(session);let w=await q;if(!w)w=(await Wallet.create([{userId}],{session}))[0];return w;}
type WalletBalanceFields={deposit:number;profit:number;commission:number;rewards:number;capitalAvailable:number;withdrawalReserved:number};
export function availableOf(w:WalletBalanceFields){return money(w.profit+w.commission+w.rewards+w.capitalAvailable-w.withdrawalReserved);}
export async function debitAvailable(userId:unknown,amount:number,session?:ClientSession){const w=await ensureWallet(userId,session);const fields=['deposit','profit','commission','rewards','capitalAvailable'];let remaining=money(amount);for(const f of fields){const walletFields=w as unknown as Record<string,number>;const cur=walletFields[f];const take=Math.min(cur,remaining);walletFields[f]=money(cur-take);remaining=money(remaining-take);if(remaining<=0)break;}if(remaining>0)throw new AppError(422,'Insufficient available balance');w.version+=1;await w.save({session});return w;}
export async function ledgerEntry(args:{userId:any,type:string,amount:number,direction:'credit'|'debit',status?:'pending'|'completed'|'rejected'|'reversed',reference:string,description:string,relatedEntity?:any,adminActorId?:any,metadata?:any},session?:ClientSession | { session: ClientSession }){const dbSession = session && ('session' in session) ? session.session : session;const amount=money(args.amount);if(amount<=0)throw new AppError(422,'Ledger amount must be positive');const transactionId='TXN-'+crypto.randomBytes(9).toString('hex').toUpperCase();const tx=(await Transaction.create([{...args,transactionId,amount}],{session:dbSession}))[0];const w=await ensureWallet(args.userId,dbSession);if((args.type==='withdrawal'||args.type==='package_purchase')&&args.direction==='debit'&&args.status==='pending'){w.withdrawalReserved=money(w.withdrawalReserved+amount);w.version+=1;await w.save({session:dbSession});return tx;}if((args.type==='withdrawal'||args.type==='package_purchase')&&args.direction==='debit'){await debitAvailable(args.userId,amount,dbSession);return tx;}if(args.type==='withdrawal'&&args.direction==='credit'){w.withdrawalReserved=money(Math.max(0,w.withdrawalReserved-amount));w.version+=1;await w.save({session:dbSession});return tx;}const field=args.type==='capital'?'capitalLocked':args.type==='capital_unlock'?'capitalAvailable':args.type==='profit'?'profit':args.type==='commission'?'commission':args.type==='reward'?'rewards':args.type==='deposit'?'deposit':args.type==='package_purchase'?'deposit':null;if(field){const delta=args.direction==='credit'?amount:-amount;const walletFields=w as unknown as Record<string,number>;const current=walletFields[field];if(delta<0&&current+delta<0)throw new AppError(422,'Insufficient balance');walletFields[field]=money(current+delta);w.version+=1;await w.save({session:dbSession});}return tx;}
export async function withTransaction<T>(fn:(session:ClientSession)=>Promise<T>){const session=await mongoose.startSession();try{let result!:T;await session.withTransaction(async()=>{result=await fn(session);});return result;}finally{await session.endSession();}}


